config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "stories#index"
  resources :stories do
    resources :sentences
  end
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  validates :content, :image_url, presence: true
  belongs_to :user
  belongs_to :story
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
  has_many :sentences
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  has_many :sentences
  has_many :stories

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :set_sentence, only: [:show, :destroy, :edit, :update]
  before_action :set_story, only: [:show, :destroy, :edit, :update]

  def index
  end

  def new
    @current_image = Dir.new(Rails.root.to_s + "/app/assets/images").to_a.select{|f|    f.downcase.match(/\.jpg|\.jpeg|\.png/) }.sample
    @story = Story.find(params[:story_id])
    @sentence = Sentence.new
  end

  def create
    @story = Story.find(params[:story_id])
    @sentence = @story.sentences.new(sentence_params)
    if @sentence.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @sentence.update(sentence_params)
      redirect_to story_sentence_path(@story, @sentence)
    else
      render :edit
    end
  end

  def destroy
    if @sentence.destroy
      redirect_to story_path(@story)
    else
      redirect_to story_path(@story)
    end
  end

  private

  def set_sentence
    @sentence = Sentence.find(params[:id])
  end

  def set_story
    @story = Story.find(params[:story_id])
  end

  def sentence_params
    params.require('sentence').permit(:content, :user_id, :story_id, :image_url)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_user, only: [:create]
  before_action :set_story, only: [:show, :destroy, :update, :edit]

  def index
    @stories = Story.all
  end

  def show
    @sentences = @story.sentences
  end

  def new
    @story = Story.new
  end

  def create
    @story = @user.stories.new(story_params)
    if @story.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @story.update(story_params)
      redirect_to story_path(@story)
    else
      redirect_to story_path(@story)
    end
  end

  def destroy
    if @story.destroy
      redirect_to root_path
    else
      redirect_to stories_path(@story)
    end
  end

  private

  def set_user
    @user = User.find(params[:story][:user_id])
  end

  def set_story
    @story = Story.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:title, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoryTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ye Olden Storey Tyme", root_path, class: "nav navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path, method: :get %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path, method: :get %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/sentences/_edit_sentence_form.erb
<h2>Edit Sentence</h2>
<%= image_tag @current_image %>

<%= form_for [@story, @sentence] do |f| %>
  <%= f.hidden_field :image_url, value: @sentence.image_url %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :story_id, value: story.id %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit "Edit sentence" %>
<% end %>

app/views/sentences/_sentence_form.html.erb
<h2>New Sentence</h2>
<%= image_tag @current_image %>

<%= form_tag(controller: "sentences", action: "create", method: "post") do %>
  <%= hidden_field_tag :image_url, @current_image %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :story_id, story.id %>
  <%= label_tag :content %>
  <%= text_field_tag :content %>
  <%= submit_tag "Add sentence" %>
<% end %>

app/views/sentences/edit.html.erb
<%= render partial: 'edit_sentence_form', locals: {story: @story, sentence: @sentence} %>

app/views/sentences/new.html.erb
<%= render partial: 'sentence_form', locals: {story: @story} %>

app/views/sentences/show.html.erb
<%= image_tag @sentence.image_url %><br />
<%= @sentence.content %><br />

<%= link_to 'Edit', edit_story_sentence_path(@story, @sentence) %><br />

<%= link_to(story_sentence_path(@story, @sentence),
  data: {
    confirm: 'Delete sentence?',
    method: 'delete'}) do %>
    Delete Sentence
  <% end %>

app/views/stories/_edit_story_form.erb
<h2>Edit Story</h2>

<%= form_for story do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit "Edit Story" %>
  </div>
<% end %>

app/views/stories/_story_form.html.erb
<h2>New Story</h2>

<%= form_for @story do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit "Create Story" %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<%= render partial: "edit_story_form", locals: {story: @story} %>

app/views/stories/index.html.erb
<h1>Welcome to Story Time Fun Land Place Thing</h1>

<% @stories.each do |story| %>
  <%= link_to story.title, story_path(story) %><br>
<% end %>

<br><br><%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<%= render partial: 'story_form' %>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<% @sentences.each do |sentence| %>
  <%= link_to sentence.content, story_sentence_path(@story, sentence) %>
<% end %>
<br /><br />
<%= link_to 'Add new sentence', new_story_sentence_path(@story ) %>
<br /><br />

<%= link_to 'Edit Story', edit_story_path(@story) %><br />
<%= link_to(story_path(@story),
  data: {
    confirm: 'Delete story?',
    method: 'delete'}) do %>
    Delete Story
  <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>